### ISSUE TITLE
Soumission de dépêche manquante dans l'historique

### ISSUE THREAD

**Issue by zeroheure** [mjourdan/linuxfr-design#2]
Dans la modification autour de la rédaction des articles (poussée ce jour sur linuxfr), le nouvel historique ne contient plus la date et l'auteur de la soumission de la dépêche. 
Or ça aide en modération de voir qu'il y a eu des corrections par des collègues modérateurs car ça prouve qu'on a relu.

**Comment by nono** [comment]
Humm, je ne suis pas sûr de comprendre de quoi tu parles. Il n'y a pas eu de changement sur ça (enfin, sauf si je me suis raté quelque part).

L'historique est maintenant replié par défaut, mais il contient exactement la même chose qu'avant : les éditions avec auteur et date de modification. On affiche également la date et l'auteur de la soumission, mais ça se fait dans la tribune et uniquement pour les dépêches poussées via l'espace de rédaction.

**Comment by zeroheure** [comment]
Le 11 mars, 13:46:58 Bruno Michel a écrit :
> Humm, je ne suis pas sûr de comprendre de quoi tu parles. Il n'y a pas eu de
> changement sur ça (enfin, sauf si je me suis raté quelque part).
> 
> L'historique est maintenant replié par défaut, mais il contient exactement
> la même chose qu'avant : les éditions avec auteur et date de modification.
> On affiche également la date et l'auteur de la soumission, mais ça se fait
> dans la tribune et uniquement pour les dépêches poussées via l'espace de
> rédaction.

Ma mémoire imparfaite pense que  la date et l'auteur de la soumission étaient 
dans l'historique.

**Comment by nono** [comment]
J'ai été vérifié sur alpha, sur lequel les dernières modifications n'ont pas encore été déployées : la date et l'auteur de la soumissions n'apparaissent pas dans l'historique.
